### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by maniarpratik** [philbertphotos/osticket-bootstrap-theme#10]
Hello There is responsive design issue with homepage.

**Comment by kenmarple** [comment]
What is the square next to the sign in area? 
it seems to be missing graphics buttons?

![2017-09-06 09_37_27-the pure synthetic company](https://user-images.githubusercontent.com/19368491/30123808-09b8dd9c-92e8-11e7-92cb-575ecc862a9b.png)
![2017-09-06 09_39_35-](https://user-images.githubusercontent.com/19368491/30123817-0f963458-92e8-11e7-819c-dd922f0f09ba.png)

**Comment by jdyach** [comment]
My site looks like the above screenshots from @kenmarple. Not looking like the demo at all. The HTML structure is totally different. Why is this?

**Comment by stamatisv** [comment]
guys about the icon, it's missing some bootstrap fonts. A quick workaround is to get https://github.com/twbs/bootstrap/archive/v3.3.6.zip , unzip it and copy bootstrap-3.3.6/fonts/glyphicons-halflings-regular.* to osticket install dir assets/default/fonts/

**Comment by TheRayJohnson** [comment]
Same as above screenshot, @philbertphotos
