### ISSUE TITLE
problem with guest user tickets

### ISSUE THREAD

**Issue by timothymichel2000** [philbertphotos/osticket-bootstrap-theme#11]
The Open a New Ticket screen does not display email address - even though this is a form requirement.
Tim M.

**Comment by ytyeoh** [comment]
I fix the bugs but unable push a code for pull request.

**Comment by geo782** [comment]
Hi,
I have same problem. All fields in contact information form of New ticket screen are gone and i cannot submit ticket because they are required.

**Comment by ikef** [comment]
To fix this restore the following code in include/client/open.inc.php within the form with id #ticketForm:
```php
  <?php
        if (!$thisclient) {
            $uform = UserForm::getUserForm()->getForm($_POST);
            if ($_POST) $uform->isValid();
            $uform->render(false);
        }
        else { ?>
            <tr><td colspan="2"><hr /></td></tr>
        <tr><td><?php echo __('Email'); ?>:</td><td><?php
            echo $thisclient->getEmail(); ?></td></tr>
        <tr><td><?php echo __('Client'); ?>:</td><td><?php
            echo Format::htmlchars($thisclient->getName()); ?></td></tr>
        <?php } ?>
```

**Comment by rpoyanco** [comment]
> To fix this restore the following code in include/client/open.inc.php within the form with id #ticketForm:

kemikaike is right....it is the solution....
Really thank you! is very weird that after osticket is working and then replace the files with this theme...it doesn't work any more.
Thank you @kemikaike for publish this fix.

**Comment by FaserF** [comment]
@kemikaike Thanks for the fix, but it does not work for me. I get a white blank screen.
I think I dont get it where exactly I have to put in your code inside the id ticketForm

Edit:
you have to paste the code right after:

```
<div id="dynamic-form">
        <?php foreach ($forms as $form) {
            include(CLIENTINC_DIR . 'templates/dynamic-form.tmpl.php');
        } ?>
    </div>
    <tbody>
```
