### ISSUE TITLE
Theme not compatible for last osticket version(security update) Request update

### ISSUE THREAD

**Issue by ghost** [philbertphotos/osticket-bootstrap-theme#15]
Hello,
after applied theme files, interface doesnt same as on the demo
#unable view two separate large window
#background only black, even change page_bg picture doesnt apply to client background

demo http://ppsdemo.vide.vi/
after last ver,http://prntscr.com/izlcr7

**Comment by gusleig** [comment]
Could you get a fix for this?

**Comment by reardoncomm** [comment]
I would also like fix for this issue.

**Comment by vegagiancarlo** [comment]
Same issue, I have review the code and but nothing that fix it.

**Comment by Alexwlt** [comment]
Body background color + other CSS can be changed in assets/default/css/bootstrap-theme.css

**Comment by vegagiancarlobz** [comment]
> Same issue, I have review the code and but nothing that fix it.

First of all I did not write this yet why did the ticket redirect me to this? I mean I have a dispute with Envato over this and already leaved my review.

**Comment by philbertphotos** [comment]
Its fixed
