### ISSUE TITLE
No ticket  view and no dynamic-form

### ISSUE THREAD

**Issue by leroy23** [philbertphotos/osticket-bootstrap-theme#19]
Hi i have this problems:
1- A user can't view tickets
![Cattura](https://user-images.githubusercontent.com/6893454/59549791-05010d00-8f63-11e9-8a78-57902d56dafb.PNG)
2- not found the dynamic-form in select topic
![Cattura2](https://user-images.githubusercontent.com/6893454/59549789-05010d00-8f63-11e9-95b8-fe81165bd52e.PNG)

can you help me?

**Comment by saikatkoleyaccellier** [comment]
For this just change the class name in "tickets.inc.php" file. Search by "$tickets = TicketModel::objects();"  and replace with "Ticket::objects();". I hope then you will be able see the list.

**Comment by philbertphotos** [comment]
Its been updated to 1.14.1 demo reestablished .
