### ISSUE TITLE
header.inc.php

### ISSUE THREAD

**Issue by rhcpdu13** [philbertphotos/osticket-bootstrap-theme#2]
Hi!

In this file, is a little issue in the line 109 :
`<li>a class="flag flag-<?php echo strtolower($locale ?: $info['flag'] ?: $lang); ?>"`

you forget "<" after `<li>`

And can you add a drop-down menu for this icon ? i think it will be better :)

Good luck and good work ! :)

**Comment by philbertphotos** [comment]
This has been fixed and will be updated shortly... thanks you.
BTW I will this to a drop box :)
