### ISSUE TITLE
No commenting area and not showing previous comment 

### ISSUE THREAD

**Issue by saikatkoleyaccellier** [philbertphotos/osticket-bootstrap-theme#20]
Hi,

When an user is logged in and clicking a ticket which he/she has created then only ticket details is showing but no comment is coming and as well as the put comment section is not coming also.

![StaticShot_10-07-2019_08-25-25](https://user-images.githubusercontent.com/51364858/60936897-54312800-a2ec-11e9-895b-9c2cdd954892.png)

**Comment by philbertphotos** [comment]
Its been updated to 1.14.1 demo reestablished .
