### ISSUE TITLE
cannot view some fields 

### ISSUE THREAD

**Issue by consocio** [philbertphotos/osticket-bootstrap-theme#21]
I cannot view some fields in the support request. Like name, mail, telephone so I can't send a support request without these

**Comment by gastondc** [comment]
I have Osticket version: 1.12

On the portal client don't work to generate new ticket, because the mandatory field don't show: Username, mail and company.

any idea ? 

Thanks!

**Comment by kintaro1981** [comment]
I think that this project is dead.
Osticket latest version is 1.14 and this theme supports 1.10

**Comment by philbertphotos** [comment]
Its been updated to 1.14.1 demo reestablished .
