### ISSUE TITLE
Problem with editing ticket summary

### ISSUE THREAD

**Issue by bcrownover** [philbertphotos/osticket-bootstrap-theme#23]
When the end user clicks the Edit link to edit the ticket title, a link like /tickets.php?a=edit&id=7 is used to open the editor. However, with the theme applied, the editing form fails to load. The error I see in the logs is:

> [16-Jul-2020 23:16:29 UTC] PHP Fatal error:  Uncaught Error: Unsupported operand types in /var/www/html/include/class.dynamic_forms.php:1188
Stack trace:
#0 /var/www/html/include/client/edit.inc.php(21): DynamicFormEntry->render(0)
#1 /var/www/html/tickets.php(147): include('/var/www/html/i...')
#2 {main}
  thrown in /var/www/html/include/class.dynamic_forms.php on line 1188

My environment:

Server Information
osTicket Version | v1.14.2 (cba6035) —  Up to date
Web Server Software | Apache/2.4.37 (centos) OpenSSL/1.1.1c mod_auth_gssapi/1.6.1
MySQL Version | 8.0.17
PHP Version | 7.2.24

**Comment by FedorSabeshkin** [comment]
@bcrownover, i have same problem
Did you resolve it?



My environment:

Server Information
osTicket Version | 1.14-git 
Web Server Software | Apache/2.4.46 (Win64) OpenSSL/1.1.1g PHP/7.4.10
SQL Version | 10.4.14-MariaDB
PHP Version | 7.4.10

**Comment by philbertphotos** [comment]
fixed
