### ISSUE TITLE
Input forms missing

### ISSUE THREAD

**Issue by mattish91** [philbertphotos/osticket-bootstrap-theme#24]
All input fields at missing in all user specific forms, even after a manually registered account where the user needs to change password.

To confirm this issue please check here: helpdesk.mspot.nu

There is no fields when you press "create account" or when I have manually created an account from an email support ticket.

![Screenshot_20200721-010401](https://user-images.githubusercontent.com/6743307/87994891-5c6e9680-caee-11ea-8ce7-18b1509be873.jpg)

**Comment by philbertphotos** [comment]
fixed
