### ISSUE TITLE
Missing contact information section

### ISSUE THREAD

**Issue by zackchadwick** [philbertphotos/osticket-bootstrap-theme#26]
Running version 1.15 of OSTicket. Using this package breaks creating a new ticket. The contact information form that's required to be filled out to allow guests to list an email address does not show on the create ticket page.

I plan on taking a look in a few days if I have time for fixing it, but wanted to make you aware. I'll put in a pull request if I correct it.

**Comment by djzwerg** [comment]
@zackchadwick I recognized the same issue. Did you solve this yet?

**Comment by philbertphotos** [comment]
I need to install/upgrade to 1.15 to fix this .. been lazy.

**Comment by djzwerg** [comment]
I'd fix this within the PR

**Comment by philbertphotos** [comment]
Ok merged it
