### ISSUE TITLE
Bootstrap isn't loading corretly.

### ISSUE THREAD

**Issue by Thiritin** [philbertphotos/osticket-bootstrap-theme#4]
I  installed a fresh copy of the current osticket RC2. Antything i see is this http://support.novarp.de

Did i miss something?

**Comment by philbertphotos** [comment]
It loaded for me i will check on a computer but I suspect its working on both..

**Comment by Thiritin** [comment]
Now its working. I think it was because of the cloudflare cache. Anyways, thank you!
