### ISSUE TITLE
A site is buggy

### ISSUE THREAD

**Issue by Thiritin** [philbertphotos/osticket-bootstrap-theme#5]
The Thank you Page is buggy. 

See what i mean.

http://i.imgur.com/RGpAgS5.jpg

**Comment by philbertphotos** [comment]
I will fix it.

**Comment by charlestruluck** [comment]
I've got it. I'll make a push soon

**Comment by philbertphotos** [comment]
thanks for that I will do a pull.

**Comment by philbertphotos** [comment]
updated.
