### ISSUE TITLE
KB articles disappear behind footer

### ISSUE THREAD

**Issue by tenaki** [philbertphotos/osticket-bootstrap-theme#7]
When you add KB articles the first 5 show the rest disappear behind the footer http://screencast.com/t/O94Cmzkm

**Comment by philbertphotos** [comment]
Ok ... I have an update coming this weekend that will fix several bugs this being one of them thanks to you reporting it.

**Comment by tenaki** [comment]
Welcome, really nice template, btw

**Comment by tenaki** [comment]
Sorry, this was my own issue, just worked it out
