### ISSUE TITLE
 Responisve für v1.10-rc.3

### ISSUE THREAD

**Issue by Diedrichs** [philbertphotos/osticket-bootstrap-theme#8]
Hallo

Wird es für diese Osticket-Version eine Anpassung geben? Ich habe es kurz ausprobiert, da kommt es aber mit dem Anlegen eines neuen Tickets zu Problemen.

Will there be an adjustment for this osTicket version? I tried it briefly, but since it comes with the creation of a new ticket to problems. (translated with Google)

Liebe Grüße / Best regards
Harald

**Comment by philbertphotos** [comment]
Yes I am currently updating it.

**Comment by meinsteren** [comment]
Hallo Harald,

Ich benutze die Version v1.9.14 mit time spent. es funktioniert sehr gut. 

ich habe auch es kurz  ausprobiert die Version v1.10-rc.3 und hat kleine fehler(buttom cancel new ticket).

mfg
Renzo

**Comment by Diedrichs** [comment]
Hallo Renzo!

Was ist time spent?

Also bei mir kommt es unter  der v1.10-rc.3 zu einer Fehlermeldung. Ein Ticket kann erstellt werden. Wenn aber der Kunde dieses Ticket aufruft kommt es zu einer Fehlermeldung. Di Meldung stört zwar nicht, aber ich denke, daß das keinen guten Eindruck beim Kunden macht. Weshalb ich es mit dieser Meldung nichz einsetzen will. Siehe Anlage!

Liebe Grüße
Harald

Hello Renzo!

What is time spent?

So for me there is an error message under the v1.10 rc.3. A ticket can be created. But if the customer calls this ticket there is an error message. The message may not interfere, but I think that makes a good impression with the customer. Why I do not want to use it with this message. See Attachment!

best regards
Harald

![08-09-_2016_01-13-45](https://cloud.githubusercontent.com/assets/5257366/18331990/3c6f4f44-7563-11e6-9584-7fcbe350e722.jpg)

**Comment by meinsteren** [comment]
Hi Harald,
Time spent ist Time Tracking(zeitlösung eines ticket).

![ticket](https://cloud.githubusercontent.com/assets/22029754/18344278/ec385792-75b6-11e6-9f35-6d7e67ae54c9.png)

**Comment by meinsteren** [comment]
ich bin ausprobiert [https://github.com/osTicket/osTicket/compare/develop-next...greezybacon:feature/time-tracking-11](url)

**Comment by philbertphotos** [comment]
I have to look into the Time Spent checking Mod

**Comment by Diedrichs** [comment]
What can I do?

@meinsteren 
The Link doesn't work

**Comment by meinsteren** [comment]
Hi Harald,

Search: Feature / Time Tracking v1-10-x #3231

**Comment by philbertphotos** [comment]
Updated the 1.10 final
