### ISSUE TITLE
Can't View Ticket Details

### ISSUE THREAD

**Issue by Darex2094** [philbertphotos/osticket-bootstrap-theme#9]
When a client clicks on a ticket to view the ticket's thread and details, the user is unable to see the thread and details.

![chrome_2016-11-10_07-20-30](https://cloud.githubusercontent.com/assets/8104260/20180098/381ce25a-a716-11e6-887d-59f722cf0343.png)

**Comment by philbertphotos** [comment]
I have a fix for that. I will update it.

**Comment by Darex2094** [comment]
Thank you. I'd be happy to test it. I notice you don't have a devel branch.

**Comment by Darex2094** [comment]
Haven't seen any new commits. Just curious what the status is.

**Comment by maniarpratik** [comment]
Ticket view details still not displaying ticket.
Have you not commited yet?

**Comment by philbertphotos** [comment]
Can you post a screenshot?

**Comment by maniarpratik** [comment]
![support_issue](https://user-images.githubusercontent.com/15357027/26986632-fabdcfcc-4d65-11e7-883b-2fc8a8d94228.png)

**Comment by maniarpratik** [comment]
After subject its not displaying anything.Samething happening in edit ticket.

**Comment by DDaehn** [comment]
Hi,
first thank you for the great theme. Good work there.

But we have the same problem that maniarpratik already has described. 
After the header nothing is dispayed. Same thing for the edit ticket site.

![screen2](https://user-images.githubusercontent.com/29476297/27215519-f1cea48e-5271-11e7-9e2e-93891b3eeda5.png)
![screen1](https://user-images.githubusercontent.com/29476297/27215520-f1d21a88-5271-11e7-8159-c9ec45e32513.png)

To fix this issue we have added the orignal view.inc.php. and the thread-entries.tmpl. This shows the messages again, but it not fully responsive and doesnt look as good as before.

**Comment by philbertphotos** [comment]
Update the entire There to what I currently run for 1.10 Final its been in constant development but did not update git up.

**Comment by philbertphotos** [comment]
Try it ad let me know how it works.

**Comment by maniarpratik** [comment]
Ok thanks

Thank You,
With Regards,
Pratik Maniar
Mo.No. : +91 7383739372

**Comment by OldManBrook** [comment]
This is a great responsive theme for osTicket, the only issue being the existing Support Centre logo is a Black Text transparent image.

I have changed the file \assets\default\images\logo.png to white text transparent and it shows up great on the black background.

![logo](https://user-images.githubusercontent.com/6135980/39550860-ac925ff6-4e5a-11e8-9779-b9905cb1236b.png)

Thanks @philbertphotos , great work.

Have you any plans for the agent backend as well ?

All the best
